// Generate self-consistent synthetic load.network fixtures with valid
// MPT proofs. Run when:
//   - first time (no live load.network access yet)
//   - real fixtures need to be regenerated after API shape drift
//   - test surface expands to new addresses/slots
//
// Output: well-formed JSON files in ../fixtures/ that look like real
// load.network responses but use a synthesised state trie. The proofs
// are valid MPT proofs against the synthesised state root, so
// `verifier.mjs` actually verifies them — meaning CI exercises real
// MPT walking, not a stubbed pass-through.
//
// Usage:
//   node load-network/fixtures/synthesise.mjs
//
// The output is committed (this is the CI fixture). Re-run if the
// fixture shape needs to change; otherwise leave alone.

import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

import { Trie } from '@ethereumjs/trie';
import { bytesToHex, bigIntToBytes } from '@ethereumjs/util';
import { keccak256 } from 'ethereum-cryptography/keccak.js';

import {
  encodeAccount,
  encodeStorageValue,
  deriveAccountKey,
  deriveStorageKey,
} from '../verifier.mjs';

const here = dirname(fileURLToPath(import.meta.url));

// ─── Anchor parameters (kept aligned with the build-map narrative) ───
const BLOCK_NUMBER = 19_000_000;
const ADDRESS      = '0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2'; // WETH
const SLOT         = '0x0';
const SLOT_VALUE   = '0x577261707065642045746865720000000000000000000000000000000000001a';

const ACCOUNT_INPUTS = {
  nonce:    1n,
  balance:  0n,
  codeHash: '0xb44d950b2cf81c7c4e7b0e1c7bce3a3b1f3c5d7e9b1c3d5e7f9a1b3c5d7e9f12',
};

// ─── Build the storage trie ─────────────────────────────────────────────
// One-slot synthetic storage; enough for a real proof, small enough to
// commit. Anchor slot is what reconstruct.test.mjs queries.
const storageTrie = await Trie.create();
await storageTrie.put(deriveStorageKey(SLOT), encodeStorageValue(SLOT_VALUE));
const storageRoot   = storageTrie.root();
const storageProof  = await storageTrie.createProof(deriveStorageKey(SLOT));

// ─── Build the world state trie ─────────────────────────────────────────
const account = { ...ACCOUNT_INPUTS, storageRoot };
const stateTrie = await Trie.create();
await stateTrie.put(deriveAccountKey(ADDRESS), encodeAccount(account));
const stateRoot    = stateTrie.root();
const accountProof = await stateTrie.createProof(deriveAccountKey(ADDRESS));

// ─── Block envelope (block_hash is a synthesised stand-in) ──────────────
const blockHash   = bytesToHex(keccak256(new TextEncoder().encode(`block-${BLOCK_NUMBER}`)));
const archiveRoot = bytesToHex(keccak256(new TextEncoder().encode(`archive-${BLOCK_NUMBER}`)));

const blockJson = {
  block_number: BLOCK_NUMBER,
  block_hash:   blockHash,
  state_root:   bytesToHex(stateRoot),
  archive_root: archiveRoot,
  timestamp:    1704067200,
  captured_at:  'fixture/v2-mpt/2026-05-02',
  fixture_note: 'Synthesised stand-in for a real load.network archive bundle. Generated by load-network/fixtures/synthesise.mjs — every proof in this fixture is a valid MPT proof against the synthesised state and storage roots, so CI exercises the real verifier walk. Replace via fixtures/record.mjs once API access is provisioned.',
};

const accountJson = {
  block_number:  BLOCK_NUMBER,
  address:       ADDRESS,
  balance:       '0x' + (account.balance ?? 0n).toString(16),
  nonce:         '0x' + (account.nonce ?? 0n).toString(16),
  code_hash:     account.codeHash,
  storage_root:  bytesToHex(storageRoot),
  account_proof: accountProof.map((n) => bytesToHex(n)),
};

const storageJson = {
  block_number:  BLOCK_NUMBER,
  address:       ADDRESS,
  slot:          SLOT,
  value:         SLOT_VALUE,
  storage_proof: storageProof.map((n) => bytesToHex(n)),
};

const manifestJson = {
  block_number:        BLOCK_NUMBER,
  anchor_address:      ADDRESS,
  anchor_slot:         SLOT,
  captured_at:         'fixture/v2-mpt/2026-05-02',
  captured_via:        'load-network/fixtures/synthesise.mjs',
  load_network_endpoint: 'synthesised (no network access; deterministic)',
  files: [
    `block_${BLOCK_NUMBER}.json`,
    `account_${BLOCK_NUMBER}_weth.json`,
    `storage_${BLOCK_NUMBER}_weth_slot0.json`,
  ],
  note: 'Synthesised fixture v2: includes account_proof and storage_proof arrays that verify against the synthesised state_root via load-network/verifier.mjs. Refresh via record.mjs once Load Network API access is provisioned and the live shape is known to match.',
};

writeJson(resolve(here, `block_${BLOCK_NUMBER}.json`), blockJson);
writeJson(resolve(here, `account_${BLOCK_NUMBER}_weth.json`), accountJson);
writeJson(resolve(here, `storage_${BLOCK_NUMBER}_weth_slot0.json`), storageJson);
writeJson(resolve(here, 'MANIFEST.json'), manifestJson);

console.log('synthesised:');
console.log(`  state_root:    ${bytesToHex(stateRoot)}`);
console.log(`  storage_root:  ${bytesToHex(storageRoot)}`);
console.log(`  account_proof: ${accountProof.length} nodes`);
console.log(`  storage_proof: ${storageProof.length} nodes`);
console.log(`fixtures written to ${here}`);

function writeJson(path, body) {
  writeFileSync(path, JSON.stringify(body, null, 2) + '\n');
}
